---
- name: Install httpd & tree packages
  hosts: all

  tasks:
  - name: Install the httpd package
    yum:
      name:
        - tree
        - wget 
        - httpd
      state: present


  - name: Start the httpd service
    service:
      name: httpd
      state: started
      enabled: true
