---
- name: Installing tomcat
  hosts: all
  gather_facts: false

  tasks:
  - name: Installing Java package
    yum:
      name: java
      state: present


  - name: Download Tomcat package
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
      dest: /opt
  
  - name: Untar the tomcat package
    unarchive: 
      src: /opt/apache-tomcat-8.5.85.tar.gz
      dest: /opt
      remote_src: yes

  - name: Add the execution permission
    file:
      path: /opt/apache-tomcat-8.5.85/bin/startup.sh
      mode: 0777

  - name: Start the Apache service
    shell: "./startup.sh &"
    args:
      chdir: /opt/apache-tomcat-8.5.85/bin/

    tags: Starting the apache service
